package it.polimi.ingsw.PSP43.client.graphic.gui;

import it.polimi.ingsw.PSP43.client.graphic.cli.QuitPlayerException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import java.io.IOException;
import java.util.List;


public class GuiStarter extends Application {

    private static Stage primaryStage;

    /**
     * Static method that returns the stage generated by JavaFX at the beginning of the game.
     * @return first stage (generated by JavaFX) at the beginning of the game
     */
    public static Stage getPrimaryStage() {
        return primaryStage;
    }


    public static void setPrimaryStage(Stage primaryStage) {
        GuiStarter.primaryStage = primaryStage;
    }

    /**
     * First method to be executed, it loads the FXML file with the choice between cli and gui.
     * @param primaryStage stage automatically generated from JavaFX
     */
    @Override
    public void start(Stage primaryStage) {

        GuiStarter.primaryStage = primaryStage;

        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(getClass().getResource("/FXML/game_init/home.fxml"));

        try {
            Scene scene = new Scene(loader.load());
            // set the css stylesheet for the serverIPChoice screen
            primaryStage.setScene(scene);
            scene.getStylesheets().add(getClass().getResource("/CSS/game_init/home.css").toExternalForm());
        } catch (IOException e) {
            e.printStackTrace();
        }

        // set the minimum height and width so that the window cannot be resized to lower values
        primaryStage.setMinHeight(650);
        primaryStage.setMinWidth(650);
        primaryStage.setResizable(false);
        primaryStage.show();
        primaryStage.centerOnScreen();

    }


    /**
     * Method executed when the window is closed.
     * @throws QuitPlayerException exception thrown if a player closes the window
     */
    @Override
    public void stop() throws QuitPlayerException {
        System.exit(-1);
    }

}
